micronaut:
  environment: qa
  application:
    name: micronautExplore
datasources:
  default:
    url: jdbc:mysql://localhost:3306/temp?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
        show_sql: true


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
